name: Deploy Project Using Custom Cache Actions

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: application
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Load and cache dependencies
        uses: ./.github/actions/cache
        with:
          caching: 'false'
      - name: Run tests
        id: run-tests
        run: npm test
      - name: upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: application/test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    defaults:
      run:
        working-directory: application
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Load and cache dependencies
        uses: ./.github/actions/cache
      - name: Build
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          # artifactのパスは絶対パス
          path: application/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output contents
        run: ls -la
      - name: OutPut filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying..."
  report:
    needs: [deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: |
          echo "Something went wrong"
          echo "${{ toJSON(github) }}"
