name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: configure aws credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: arn:aws:iam::1234567890:role/example-role
      #     role-session-name: samplerolesession
      #     aws-region: ap-north-east-1
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Cache NodeJS
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --production
      - name: Build and Export
        run: npm run build
      - name: Deploy To S3 Bucket
        run:
          aws s3 sync --region ap-northeast-1 ./out s3://dummy-bucket --delete