name: lambda-deploy

on:
  push:
    branches:
      - main

env:
  BUCKET_NAME: lambda-deploy-demo
  REGION_NAME: ap-northeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::XXXXXXXXXXXX:role/github-actions-deploy-lambda
          role-session-name: samplerolesession
          aws-region: ${{ env.REGION_NAME }}
      - name: Deploy Lambda Function
        # run: |
        #   zip -f package.zip backend/
        #   aws s3 cp package.zip s3://${{ env.REGION_NAME }}/
        run: aws lambda update-function-code --function-name my-function --zip-file fileb://lambda.zip
