name: lambda-deploy

# on:
#   push:
#     branches:
#       - main

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

env:
  REGION_NAME: ap-northeast-1
  FUNCTION_NAME: lambda-deploy-demo
  LAMBDA_WORKING_DIRECTORY: backend
  LAMBDA_PACKAGE_NAME: lambda

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Poetryのインストール
      - name: Install poetry
        run: pipx install poetry
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::044392971793:role/${{ env.FUNCTION_NAME }}
          role-session-name: samplerolesession
          aws-region: ${{ env.REGION_NAME }}
      - name: Check Function if Exists
        id: check-function
        continue-on-error: true
        run: |
          aws lambda get-function --function-name ${{ env.FUNCTION_NAME }}
      - name: Create and Deploy Lambda Function
        if: steps.check-function.outcome == 'failure'
        run: |
          zip -r lambda.zip .
          aws lambda create-function \
          --function-name ${{ env.FUNCTION_NAME }} \
          --runtime python3.11 \
          --handler lambda_handler \
          --zip-file fileb://lambda.zip \
          --role arn:aws:iam::044392971793:role/${{ env.FUNCTION_NAME }}
        working-directory: ${{ env.LAMBDA_WORKING_DIRECTORY }}
      # - name: Deploy Lambda Function
      #   if: steps.check-function.outcome == 'success'
      #   run: |
      #     zip -r lambda.zip .
      #     aws lambda update-function-code \
      #     --function-name ${{ env.FUNCTION_NAME }} \
      #     --zip-file fileb://lambda.zip
      #   working-directory: ${{ env.LAMBDA_WORKING_DIRECTORY }}
      # lockファイルをrequirements.txtへ出力
      # --without-hashes: 出力したファイルのハッシュを除外
      # -o(output) requirements.txt:requirements.txtとして出力
      - name: Deploy Lambda Function
        if: steps.check-function.outcome == 'success'
        run: |
          mkdir -p ${{ env.LAMBDA_PACKAGE_NAME }} && \
          poetry export -f requirements.txt --without-hashes -o requirements.txt && \
          pip install -r requirements.txt --target ${{ env.LAMBDA_PACKAGE_NAME }}
          zip -r ${{ env.LAMBDA_PACKAGE_NAME }}.zip .
          aws lambda update-function-code \
          --function-name ${{ env.FUNCTION_NAME }} \
          --zip-file fileb://${{ env.LAMBDA_PACKAGE_NAME }}.zip
        working-directory: ${{ env.LAMBDA_WORKING_DIRECTORY }}
