name: lambda-deploy

# on:
#   push:
#     branches:
#       - main

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

env:
  REGION_NAME: ap-northeast-1
  FUNCTION_NAME: lambda-deploy-demo
  LAMBDA_WORKING_DIRECTORY: backend
  LAMBDA_PACKAGE_NAME: lambda

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    defaults:
      run:
        working-directory: ${{ env.LAMBDA_WORKING_DIRECTORY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Poetryのインストール
      - name: Install poetry
        run: pipx install poetry
      # - name: Setup Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.11'
      #     cache: 'poetry'
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::044392971793:role/${{ env.FUNCTION_NAME }}
          role-session-name: samplerolesession
          aws-region: ${{ env.REGION_NAME }}
      - name: Create Zip File
        run: |
          poetry install
          poetry export -f requirements.txt --without-hashes -o requirements.txt
          # pip install --upgrade pip && pip install -r requirements.txt --target .
          pip install --upgrade pip && pip install -r requirements.txt --target ${{ env.LAMBDA_PACKAGE_NAME }}
          cp lambda_function.py ${{ env.LAMBDA_PACKAGE_NAME }}
          ls -la
          # zip -r ${{ env.LAMBDA_PACKAGE_NAME }}.zip .
          zip -r ${{ env.LAMBDA_PACKAGE_NAME }}.zip ${{ env.LAMBDA_PACKAGE_NAME }}
      - name: Check Function if Exists
        id: check-function
        continue-on-error: true
        run: |
          aws lambda get-function --function-name ${{ env.FUNCTION_NAME }}
      - name: Create and Deploy Lambda Function
        if: steps.check-function.outcome == 'failure'
        run: |
          aws lambda create-function \
          --function-name ${{ env.FUNCTION_NAME }} \
          --runtime python3.11 \
          --handler lambda_handler \
          --zip-file fileb://lambda.zip \
          --role arn:aws:iam::044392971793:role/${{ env.FUNCTION_NAME }}
      - name: Deploy Lambda Function
        if: steps.check-function.outcome == 'success'
        run: |
          aws lambda update-function-code \
          --function-name ${{ env.FUNCTION_NAME }} \
          --zip-file fileb://lambda.zip
